/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#aed500",
        "secondary": "#c6c6c7",
        "secondary-container": "#454747",
        "surface": "#131313",
        "electric-blue": "#007AFF",
        "on-tertiary-fixed-variant": "#3d4d00",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c6c6c7",
        "error-container": "#93000a",
        "primary": "#c6c6c6",
        "surface-tint": "#c6c6c6",
        "on-error": "#690005",
        "primary-container": "#000000",
        "inverse-on-surface": "#313030",
        "inverse-surface": "#e5e2e1",
        "background": "#131313",
        "tertiary-fixed": "#c7f300",
        "on-primary-fixed-variant": "#474747",
        "surface-bright": "#393939",
        "outline-variant": "#4c4546",
        "secondary-fixed": "#e2e2e2",
        "tertiary": "#aed500",
        "surface-variant": "#353534",
        "on-secondary": "#2f3131",
        "on-tertiary-container": "#667e00",
        "surface-container": "#201f1f",
        "signal-red": "#FF3B30",
        "on-secondary-fixed": "#1a1c1c",
        "error": "#ffb4ab",
        "volt-accent": "#D1FF00",
        "surface-container-low": "#1c1b1b",
        "primary-fixed": "#e2e2e2",
        "on-surface-variant": "#cfc4c5",
        "surface-dim": "#131313",
        "graphite-gray": "#1C1C1E",
        "on-primary-container": "#757575",
        "tertiary-container": "#000000",
        "outline": "#988e90",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-highest": "#353534",
        "inverse-primary": "#5e5e5e",
        "on-tertiary": "#293500",
        "on-background": "#e5e2e1",
        "on-primary": "#303030",
        "on-tertiary-fixed": "#171e00",
        "frost-white": "#F5F5F7",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-container": "#b4b5b5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "base": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Metropolis", "sans-serif"],
        "display-lg": ["Metropolis", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Metropolis", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "label-caps": ["Metropolis", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "data-mono": ["13px", { "lineHeight": "1.0", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "title-md": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-base": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
